### ISSUE TITLE
Rendering class diagrams

### ISSUE THREAD

**Issue by datavectors** [y-takey/atom-mermaid#64]
I have Atom 1.48 in Ubuntu 18.04.
I have two Atom packages relevant to mermaid ..
markdown-preview-enhanced
atom-mermaid

I like the atom-mermaid feature to export rendered diagram as svg. 
However it does not render class diagrams.

Markdown-preview-enhanced does render class diagrams, but does not export as svg.

I looked at atom-mermaid/styles/mermaid-variables.less
There are ..

/* Flowchart variables */
/* Sequence Diagram variables */
/* Gantt chart variables */

but it stops there. No reference to class diagrams.

Can atom-mermaid be extended to render class diagrams in svg?

**Comment by y-takey** [comment]
Hi @datavectors , thanks for the issue :)
I published atom-mermaid@v3.5.2 that support to export class diagram as svg. It seems works fine for me, can you try it?

**Comment by datavectors** [comment]
Thank you for responding.
I have now looked at /atom-mermaid/package.json and saw that it refers to 3.4.1

  "_from": "https://www.atom.io/api/packages/atom-mermaid/versions/3.4.1/tarball",
  "_id": "atom-mermaid@3.4.1",
  
  I uninstalled and reinstalled atom-mermaid 3.5.2 but the example class diagram still does not render correctly.
  
 The first screenshot below shows the output of atom-mermaid preview (note that I do not apply ```mermaid header).

 The second screenshot below shows the output of markdown-preview-enhanced (note that here I apply ```mermaid header)
  
 The third screenshot below shows the preview of same markdown in atom-mermaid.

**[P.S.]** Latest atom-mermaid/styles/mermaid-variables.less still does not reference class diagrams

=====================================================
**Rendered by atom-mermaid (no ```mermaid header - is that correct syntax)**

![mermaid](https://user-images.githubusercontent.com/4958509/86531139-9ddc3080-beb6-11ea-880a-12c60ae42740.png)

=====================================================
**Rendered by markdown-preview-enhanced (with ```mermaid header)**

![mermaid2](https://user-images.githubusercontent.com/4958509/86531142-a92f5c00-beb6-11ea-83f5-f9c09aea198f.png)

=====================================================
**Rendered by atom-mermaid (with ```mermaid header)**

![mermaid3](https://user-images.githubusercontent.com/4958509/86531146-b0566a00-beb6-11ea-8b57-a4a9e2ad6e7d.png)

**Comment by y-takey** [comment]
Thank you for responding.
I tried with same your mermaid text, but can't reproduce the issue. it works fine for me. Hmm... 

![ss-class-diagram](https://user-images.githubusercontent.com/1817802/86532193-e588a980-bf02-11ea-852e-0c4809dbfee3.png)

> [P.S.] Latest atom-mermaid/styles/mermaid-variables.less still does not reference class diagrams

I guess there is no problem.

**Comment by datavectors** [comment]
The only point I see is that you use extension *.mmd and I use *.md but other diagrams work so that cannot be an issue.

To try to debug this at my end, is it possible to insert console log directives into the package to see the expected output or errors in Developer Tools Console?

**Comment by datavectors** [comment]
Further clues:
(a) The class diagram does not render correctly in atom-markdown preview window.
(b) The class diagram does render correctly in markdown-preview-enhanced preview window
(c) The class diagram saves correctly as png file
(d) The class diagram does not save correctly as svg file.

The output files are attached. Note that I had to change *.svg extension to *.txt since svg is not an accepted file type to upload. Change the extension back to *.svg to view in Inkscape. A screenshot of the incorrect svg image (from Inkscape) is attached.

![classes md](https://user-images.githubusercontent.com/4958509/86540018-62af2100-bef9-11ea-8639-8d11b462b641.png)

![class md svg](https://user-images.githubusercontent.com/4958509/86540144-bd954800-befa-11ea-8ddf-f22aacd26fcb.png)

[classes.md.txt](https://github.com/y-takey/atom-mermaid/files/4875400/classes.md.txt)

**Comment by datavectors** [comment]
Adding another clue ..

I tested the svg code in an xml editor and I noticed that the xml declaration is missing as top line.
`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>`

I added this declaration line and I was able to view the svg in Brave browser. But not in Inkscape.

It is puzzling.

**Comment by y-takey** [comment]
> To try to debug this at my end, is it possible to insert console log directives into the package to see the expected output or errors in Developer Tools Console?

No, maybe you can't get some clue from console log. however there may be some clue from inspecting svg element on devtool.

---

Is the first attached file that screenshot of (c) ? If so, can you open svg file of (d) in Chrome browser?(without xml declaration)

By the way, do you have any user stylesheet on Atom?

**Comment by y-takey** [comment]
I can open attached classes.md.txt in Chrome browser on my environment.

![classes_md_svg](https://user-images.githubusercontent.com/1817802/86546197-7cd71680-bf6e-11ea-83fa-4ed3e7f7781a.jpg)

**Comment by datavectors** [comment]
Since I can work around this issue and render the svg one way or another in browser(s) the only concern now is why it does not render in Inkscape. I hope eventually to edit the svg elements.

**Comment by y-takey** [comment]
It seems a issue of mermaid-js (and livrsvg). Unfortunately atom-mermaid can't support too. sorry.
https://github.com/mermaid-js/mermaid/issues/664

**Comment by datavectors** [comment]
Thanks for identifying the root cause. I will use a workaround (browser display of svg) until issue fixed by mermaid. I will now close this issue.
